// Generated by scripts/generate-city-world.mjs; do not edit.
export const CITY_WORLD = {
  "width": 64,
  "height": 48,
  "tiles": [
    "wwwwwwwwwwwssshhhhhhhhhhhhhhhhhhhhhhffffffffffffffffffffffffffff",
    "wwwwwwwwwwwssshhhhhhhhhhhhhhhhhhhhhhffffffffffffffffffffffffffff",
    "wwwwwwwwwwwssshhhhhhhhhhhhhhhhhhhhhhffffffffffffffffffffffffffff",
    "wwwwwwwwwwwssshhhhhhhhhhhhhhhhhhhhhhffffffffffffffffffffffffffff",
    "wwwwwwwwwwwssshhhhhhhhhhhhhhhhhhhhhhffffffffffffffffffffffffffff",
    "wwwwwwwwwwsssshhhpphbbbbbbbbbhhhhpphfbbbbbbbbfffppfffffffffppfff",
    "wwwwwwwwwwsssshhhpphbbbbbbbbbhhhhpphfbbbbbbbbfffppffbbbbbbfppfff",
    "wwwwwwwwwwsssshbhpphbbbbbbbbbhbhhpphbbbbbbbbbfffppffbbbbbbfppfff",
    "wwwwwwwwwwsssshhhpphbbbbbbbbbhhhhpphfbbbbbbbbfffppffbbbbbbfppfff",
    "wwwwwwwwwwsssshhbpphbbbbbbbbbhbhhpphfbbbbbbbbfffppffbbbbbbfppfff",
    "wwwdddddddddddddddphhhhhhhhhhhhhhpphffffffffffffppffbbbbbbfppfff",
    "wwwdddddddddddddddphhhhhhhhhhhhhbpphfffffffffffbppfffffffffppfff",
    "wwwdddddddddddddddppppppppppppppppppppppppppppppppppppppppppppff",
    "wwwwwwwwwwwsppppppppppppppppppppppppppppppppppppppppppppppppppff",
    "wwwwwwwwwwwssshhhpphhhhhhhhhhhhhhpphffbbffffffffppfffffffffppfff",
    "wwwwwwwwwwwssshhhpphhhhhhhhhhhhhhpphffffffffffffppfffffffffppfff",
    "wwwwwwwwwwwssshhhpphhhbbbbhhbbbbhpphffffffffffffppffffffbffppfff",
    "wwwwwwwwwwwssshhhpphhhbbbbhhbbbbhpphffffffbbbbffppfffffffffppfff",
    "wwwwwwwwwwsssshhhpphhhbbbbhhbbbbhpphffffffbbbbffpbbbfffffffppfff",
    "wwwdddddddddddddddphhhhhhhhhhhhhhpphfbffffbbbbffppfffffbfffppfff",
    "wwwdddddddddddddddphhhhhhhhhhhhhhpphffffffbbbbffppfffffffffppfff",
    "wwwdddddddddddddddphhhhhhhhhhhhhhpphffffffffffffppfffffffffppfff",
    "wwwwwwwwwwsssshhhpphhhhhhhhhhhhhhpphfffbbbffffffppffffffffbppfff",
    "wwwwwwwwwwssppppppppppppppppppppppppppppppppppppppppppppppppppff",
    "wwwwwwwwwwssppppppppppppppppppppppppppppppppppppppppppppppppppff",
    "wwwwwwwwwwsssscccppccccccccccccccppcggggggggggggppgggggggggppggg",
    "wwwwwwwwwwwssscccppccccccccccccccppcggggggggggggppgggggggggppggg",
    "wwwwwwwwwwwssscccppbbbbbbbbbbccccppcggggggggggggppgggggggggppggg",
    "wwwwwwwwwwwssscbcppbbbbbbbbbbccccppcgbbbbbbbgggbppgggggggggppggg",
    "wwwwwwwwwwwssscccppbbbbbbbbbbccccppcgbbbbbbbggggppgbggbggbbbpggg",
    "wwwwwwwwwwwssscccppbbbbbbbbbbccbcppcgbbbbbbbggggppgggggggbbbpggg",
    "wwwwwwwwwwsssscccppbbbbbbbbbbccccppcgbbbbbbbggggppgggggggbbbpggg",
    "wwwwwwwwwwsssscccppbbbbbbbbbbccccppcgbbbbbbbggggppgbggbggbbbpggg",
    "wwwwwwwwwwsssscccppccccccccccccccppcggggggggggggppgggggggggppggg",
    "wwwwwwwwwwsssscccbpcccccccccccccbppcgggggggggggbppgggggggggppggg",
    "wwwwwwwwwwssppppppppppppppppppppppppppppppppppppppppppppppppppgg",
    "wwwwwwwwwwssppppppppppppppppppppppppppppppppppppppppppppppppppgg",
    "wwwwwwwwwwsssscccppccccccccccccccppcggggggggggggppggbbbggggppggg",
    "wwwwwwwwwwsssscccppcccbbbcccbbbccppcggggggggggggppgbggbggggppggg",
    "wwwwwwwwwwwssscccppcccbbbcccbbbccppcggggggggggggppgggggggggppggg",
    "wwwwwwwwwwwssscccppccccccccccccccppcgggggggbbbggppgggggggggppggg",
    "wwwwwwwwwwwssscccppccccccccccccccppcggggggggggggppgbgggggbbppggg",
    "wwwwwwwwwwwssscccppccccccccccccccppcggggggggggbgppgggggggggppggg",
    "wwwwwwwwwwwssscccppcbccccccccccccppcggggggggggggppgggggggggppggg",
    "wwwwwwwwwwssssccccccccccccccccccccccbgggggbggbgggggbggbggbgggggg",
    "wwwwwwwwwwssssccccccccccccccccccccccgggggggggggggggggggggggggggg",
    "wwwwwwwwwwssssccccccccccccccccccccccgggggggggggggggggggggggggggg",
    "wwwwwwwwwwssssccccccccccccccccccccccgggggggggggggggggggggggggggg"
  ],
  "walkable": [
    "g",
    "h",
    "f",
    "c",
    "s",
    "p",
    "d"
  ],
  "pointsOfInterest": [
    {
      "id": "docks",
      "name": "Old Salt Docks",
      "x": 7,
      "y": 11,
      "action": "fishing",
      "district": "harbor",
      "claimable": true
    },
    {
      "id": "market",
      "name": "Token Market",
      "x": 24,
      "y": 20,
      "action": "trading tokens",
      "district": "harbor",
      "claimable": true
    },
    {
      "id": "exchange",
      "name": "Harbor Exchange",
      "x": 24,
      "y": 10,
      "action": "balancing the books",
      "district": "harbor"
    },
    {
      "id": "fountain",
      "name": "Wishing Fountain",
      "x": 44,
      "y": 22,
      "action": "chatting",
      "district": "forum",
      "claimable": true
    },
    {
      "id": "notice",
      "name": "Notice Board",
      "x": 38,
      "y": 15,
      "action": "posting notice",
      "district": "forum"
    },
    {
      "id": "casino",
      "name": "Striped Tent",
      "x": 54,
      "y": 11,
      "action": "counting lucky stars",
      "district": "forum"
    },
    {
      "id": "workshop",
      "name": "The Makery",
      "x": 24,
      "y": 33,
      "action": "building",
      "district": "workshop"
    },
    {
      "id": "benches",
      "name": "Workshop Benches",
      "x": 26,
      "y": 40,
      "action": "tinkering",
      "district": "workshop"
    },
    {
      "id": "garden",
      "name": "Quiet Corner",
      "x": 53,
      "y": 38,
      "action": "napping",
      "district": "garden"
    },
    {
      "id": "glasshouse",
      "name": "Glasshouse",
      "x": 40,
      "y": 33,
      "action": "watering plants",
      "district": "garden"
    },
    {
      "id": "park",
      "name": "Mossy Bench",
      "x": 44,
      "y": 41,
      "action": "cloud watching",
      "district": "garden"
    }
  ]
} as const;
