name = "musebook-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "MUSEBOOK_DB"
database_name = "musebook"
database_id = "5ab6a403-309a-47c4-85c8-231449f04024"
